### ISSUE TITLE
Error in ZSH init

### ISSUE THREAD

**Issue by OscarVelandia** [black7375/BlaCk-Void-Zsh#1]
Hi, i did the installation in kde neon with konsole, zsh and powerlevel10k. When init zsh this message appears:

>zsh tmux plugin: tmux not found. Please install tmux before using this plugin.
>
> Command 'tmux' not found, but can be installed with:
> 
> sudo snap install tmux  # version 2.3, or
> sudo apt  install tmux
> 
> See 'snap info tmux' for additional versions.

how can i configure the theme to dont use tmux ?.

PD. The theme is awesome!.

**Comment by black7375** [comment]
I modified it to run only if tmux is installed.
Run `zsh-update` to check it out !!
