### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by h5jam** [black7375/BlaCk-Void-Zsh#12]
**Describe the bug**

**To Reproduce**
Tell me when it happens.

 - [x] Install
 - [ ] Run
 - [ ] Update
 - [ ] Others: *explain*

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
General
 - OS(`uname -a`):  catalina
 - ZSH(`zsh --version`): zsh 5.7.1

CheckList
 - [x] Use latest commit
 - [ ] Custom in use
 - [ ] SSH

**Additional context**

How to uninstall in mac??

**Comment by black7375** [comment]
See #3 
I'll add it to the wiki.

**Comment by h5jam** [comment]
Thank you!

**Comment by black7375** [comment]
See if you needed..
https://github.com/black7375/BlaCk-Void-Zsh/wiki/Uninstall
