### ISSUE TITLE
Problem to update

### ISSUE THREAD

**Issue by OscarVelandia** [black7375/BlaCk-Void-Zsh#13]
**Describe the bug**
When I use the comand zsh-update, appears the github login  in the console

**To Reproduce**
Type zsh-update and the github login appear

 - [ ] Install
 - [ ] Run
 - [x] Update
 - [ ] Others: *explain*

**Expected behavior**
The update process don't ask for any github account.

**Environment (please complete the following information):**
General
 - OS(`uname -a`):  5.4.23-1-MANJARO 
 - ZSH(`zsh --version`): zsh 5.8 (x86_64-pc-linux-gnu)

CheckList
 - [x] Use latest commit
 - [ ] Custom in use
 - [ ] SSH

**Comment by black7375** [comment]
The problem is caused by the developer of the zplugin removing the repo and creating a new one with zinit.
https://github.com/zdharma/zinit

I'll see if a patch is available.

**Comment by black7375** [comment]
Would you like to run the command below?

```
cd $ZPLGIN_BIN 
git remote set-url origin https://github.com/zdharma/zinit.git  
```

**Comment by OscarVelandia** [comment]
With the first command this error appear `cd: not a directory: /home/USER/.zplugin/bin/zplugin.zsh`

**Comment by black7375** [comment]
OK!!
```
Parallel Update Starts Now...
Spawning the next 15 concurrent update jobs (plugins)...
Spawning the next 15 concurrent update jobs (plugins)...
```
This is normal behavior.

I applied the `Parallel Update` feature of package manager.
https://github.com/zdharma/zinit/commit/cb673688e55db881bc047939dae842c864d2b563
https://github.com/black7375/BlaCk-Void-Zsh/commit/31265bd2e4e3b222a2e7b1ddefb3608d21d12c31

**Comment by black7375** [comment]
https://github.com/black7375/BlaCk-Void-Zsh/commit/f76fa88d9469e93d94d2f336ac4e44deaf004078
https://github.com/black7375/BlaCk-Void-Zsh/commit/6185d5d8f71f050ec6df8dabecb531cd585f68ec
Patched!!
