### ISSUE TITLE
Installing Error with LinuxBrew

### ISSUE THREAD

**Issue by black7375** [black7375/BlaCk-Void-Zsh#15]
Installation may fail due to some packages currently in LinuxBrew.

Updating ripgrep 11.0.2 to 12.0.0 failed in homebrew Ubuntu due to asciidoc
(https://github.com/Homebrew/linuxbrew-core/issues/19885)

**Comment by luxus** [comment]
maybe instead of using linux brew you can zinit provide the binary? 
here are some examples 
https://gist.github.com/abl/d004dcad84a16ddd670f5337ba5b896d

**Comment by black7375** [comment]
@luxus good suggestion.
I will remove the linux brew dependency by managing binaries such as fzf and rg with zinit.

**Comment by black7375** [comment]
The `linuxbrew` dependency has been removed from `dev` branch.

**Comment by black7375** [comment]
It took a little longer.
Removed the dependency and made it available in Docker as well.
