### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by saberzaid** [black7375/BlaCk-Void-Zsh#16]
hello how are you 

great script and save me alot of time 

i installed it as user and all is ok 

but as root i cant install , 

----------------------------------------
         BlaCk-Void Zsh Setup
----------------------------------------

--------------------
  Downloads

ID_LIKE=debian
Hit:1 http://mirror.karneval.cz/pub/linux/kali kali-rolling InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ack is already the newest version (3.3.1-1).
curl is already the newest version (7.68.0-1).
git is already the newest version (1:2.25.1-1).
powerline is already the newest version (2.7-3).
tmux is already the newest version (3.0a-2).
w3m-img is already the newest version (0.5.3-37+b1).
wmctrl is already the newest version (1.07-7+b1).
xdotool is already the newest version (1:3.20160805.1-4).
zsh is already the newest version (5.8-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Now, Install Brew.
Don't run this as root!

i want to install this script as root also to custom my root zsh profile

**Comment by black7375** [comment]
I am using [linux brew](https://docs.brew.sh/Homebrew-on-Linux) for package compatibility in various distributions.

I know brew doesn't support root by default.
You can refer this article.
[How To Install and Use LinuxBrew on a Linux VPS](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-linuxbrew-on-a-linux-vps)

**Comment by saberzaid** [comment]
thanks for replay 

ok so if i want to install another plugin , i should add the plugin folder in .zplugin then plugines folder, 

after that i open the BlaCk-Void-zsh file , where i should add the plugin command under what line ? i did it before but i forgot :(

**Comment by saberzaid** [comment]
im talk about this plugin how to add it inside the Black-void-zsh 

https://github.com/stevemcilwain/quiver

**Comment by black7375** [comment]
It is easy to use additional plugins.

[Customize - Add plugin](https://github.com/black7375/BlaCk-Void-Zsh/wiki/Customize#lets-start-custom-)


1. Create `.zplugin` file at home
```shell
touch ~/.zplugins
```

2. Add to plugin
[Zinit Useage](https://github.com/zdharma/zinit#example-usage)

Perhaps adding the following command should work.
```shell
zinit light stevemcilwain/quiver
```

3. reload
