### ISSUE TITLE
Slow start up / resetting on startup

### ISSUE THREAD

**Issue by wisemandenny** [black7375/BlaCk-Void-Zsh#17]
**Describe the bug**
When I open a new zsh shell, it takes around 2 seconds to start. There is strange behavior as well: it loads the zsh prompt, then the prompt disappears and reappears after a short delay. This makes zsh pretty hard to use. I have included a video and the output from zsh/zprof.

Further, when this new shell does finally appear, it takes quite a long time for the prompt to become interactive. You can see this in the video before "zshzshzhszhshzshzs" appears. (I am typing zsh repeatedly before the prompt becomes interactive).

**To Reproduce**
Any time I run ZSH.

**Expected behavior**
Shouldn't take so long too load, definitely shouldn't "refresh".

**Screenshots**
https://youtu.be/rmL7wT9aRA4
[zprof.txt](https://github.com/black7375/BlaCk-Void-Zsh/files/4731825/zprof.txt)

~~~
**Environment (please complete the following information):**
General
 - OS: Windows 10 2004
- Running WSL2 with Ubuntu 20.04

**Comment by ilikeballoons** [comment]
update: i reinstalled ubuntu, zsh, and black-void. The startup time is greatly reduced, but still it is "refreshing".

**Comment by black7375** [comment]
**Performance**
* **Start Time:** It's made with some care, but if IO is slow, it can cause problems (not SSD, VM, WSL).
* **Interactive:** This is because the prompt is designed to be visible first during loading. It takes a lot of effort to further reduce the current start time.

**Refesh(Flickering)**
It doesn't happen on native Linux.
I think it should install WSL to find out.

**Comment by wisemandenny** [comment]
Found a fix for this, thought it might be a good idea to include it in the README.

https://github.com/microsoft/WSL/issues/4256#issuecomment-509051495

**Comment by black7375** [comment]
Reflected in [Wiki:Error](https://github.com/black7375/BlaCk-Void-Zsh/wiki/Error) and specified in README.
