### ISSUE TITLE
macOS Install Error

### ISSUE THREAD

**Issue by sdrstone1** [black7375/BlaCk-Void-Zsh#19]
**Describe the bug**

Running install script asks `sudo` permission, and brew throws permission error.

```
kollhong@Macintosh-4 ~ % bash ~/.zsh/BlaCk-Void-Zsh.sh
----------------------------------------
         BlaCk-Void Zsh Setup
----------------------------------------

--------------------
  Downloads

Password:
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
kollhong@Macintosh-4 ~ %  
```

to install this BlaCk-Void-Zsh, I commented out the 30th line (`sudo pacapt -Sy`)
and manually ran command `sudo pacapt -Sy` before running install script. 

I thought sudo permission affects one single line, but it seems that `sudo` permission affects subsequent commands.

**To Reproduce**
Tell me when it happens.

 - [X ] Install
 - [ ] Run
 - [ ] Update
 - [ ] Others: *explain*

```
git clone https://github.com/black7375/BlaCk-Void-Zsh.git ~/.zsh
bash ~/.zsh/BlaCk-Void-Zsh.sh
```

**Expected behavior**

install BlaCk-Void-Zsh

**Screenshots**

**Environment (please complete the following information):**
General
 - OS(`uname -a`): macOS 10.15.7 on iMac 5K 2015
Darwin Macintosh-4.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
 - ZSH(`zsh --version`): zsh 5.8 (x86_64-apple-darwin19.3.0)

CheckList
 - [V] Use latest commit
 - [ ] Custom in use
 - [ ] SSH

**Additional context**

**Comment by black7375** [comment]
Ok, I'll fix it.

**Comment by black7375** [comment]
My current Mac is broken and I couldn't test it.
Test if it works after performing `git pull`.

**Comment by sdrstone1** [comment]
Thank you.
I will try it tonight.

**Comment by sdrstone1** [comment]
Sorry for late...
I did uninstall and install again.
it works very well.

**Comment by black7375** [comment]
Ok, have a nice day.

**Comment by black7375** [comment]
1. eef
2. dfdf

f

1) dd
