### ISSUE TITLE
Error when running BlaCk-Void-Zsh.sh on Manjaro Linux

### ISSUE THREAD

**Issue by Perseus-Kane** [black7375/BlaCk-Void-Zsh#2]
When I run the installation script, this always shows up at the end

> Apply Settings
> 
> /home/pkane21/.zshrc found.
> Now Backup..
> '/home/pkane21/.zshrc' -> '/home/pkane21/.zshrc.bak'
> /home/pkane21/.zshenv not found.
> /home/pkane21/.zlogin not found.
> Changing shell for root.
> chsh: Shell not changed.
> ./BlaCk-Void-Zsh.sh: line 156: zcompile: command not found

I'm not sure what I'm doing wrong and I can't figure out the fix by myself. I'd really like some assistance with this

**Comment by black7375** [comment]
Sorry.. :cry:
`zcomplie` is my mistake.

Is `chsh` not a running too?
That original command is`sudo chsh -s $(which zsh)`.(need `sudo` permission)
When I tried on Manjaro, there was no error.

If it does not work, run `sudo chsh -s /bin/zsh`.
