### ISSUE TITLE
tmux 설치 부분 건의사항

### ISSUE THREAD

**Issue by BonFire145** [black7375/BlaCk-Void-Zsh#21]
black7375/BlaCk-Void-Tmux 에 이슈보드가 안보여서 여기다 작성합니다.

![image](https://user-images.githubusercontent.com/43255234/105505136-f0265700-5d0b-11eb-873e-e4baff5b2726.png)

이 부분에서,
git clone https://github.com/black7375/BlaCk-Void-Tmux.git .tmux

.tmux라 말고 ~/.tmux 라고 고쳐주셔야할 것 같아요.

**Comment by black7375** [comment]
앗 적용했습니다. 감사합니다.
