### ISSUE TITLE
오류가 발생을 합니다...ㅠㅠ

### ISSUE THREAD

**Issue by junsik5477** [black7375/BlaCk-Void-Zsh#25]
BlaCk-Void-Zsh를 잘만들어 주셔서 잘사용을 하고 있습니다.

사용중 약간의 오류?? 메세지가 확인이 되어 이렇게 글을 작성합니다.

언제 시간나실때 한번 살펴봐 주시면 감사하겠습니다.

os : macOS Big Sur 11.2.3 

## 오류 내용은 아래와 같습니다.
```shell
> source ~/.zshrc
init:pyenv initialization not cached, caching output of: init:pyenv
(eval):5: defining function based on alias `pyenv'
(eval):5: parse error near `()'
This theme is not available.
```

@ .zshrc 파일의 내용은 아래와 같습니다.
```shell
   if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
     source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
   fi
  
  export FZF_BASE=/usr/local/opt/fzf/install
  set rtp+=/usr/local/opt/fzf
  export PATH="$HOME/.pyenv/bin:$PATH"
  export PATH="/usr/local/bin:$PATH"
  export LDFLAGS="-L/usr/local/opt/zlib/lib"
  export CPPFLAGS="-I/usr/local/opt/zlib/include"
  export PATH="/usr/local/opt/icu4c/bin:$PATH"
  export PATH="/usr/local/opt/icu4c/sbin:$PATH"
 
  alias python=/Users/jskim/.pyenv/versions/3.8.8/bin/python3
  alias pip=/Users/jskim/.pyenv/versions/3.8.8/bin/pip3

  code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}
 
 
  [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
 
  if command -v pyenv 1>/dev/null 2>&1; then
   eval "$(pyenv init -)"
  fi
 
 29 source /Users/jskim/.zsh/BlaCk-Void.zshrc
```

**Comment by black7375** [comment]
pyenv는
https://github.com/black7375/zsh-lazyenv/blob/master/autoload/pyenv

여기서 초기화 됩니다.

```shell
 if command -v pyenv 1>/dev/null 2>&1; then
   eval "$(pyenv init -)"
fi
```
이 필요없을거에요.

혹시라도 lazyenv 구성상 문제가 있을수 있는데 내일 저녁쯤이면 고쳐져있을겁니다.

**Comment by black7375** [comment]
```shell
if command -v pyenv 1>/dev/null 2>&1; then
   eval "$(pyenv init -)"
fi
```
를 제거하고

`zsh-update` 실행 후 동일 증상이 생기는지 확인해주시겠어요?

**Comment by black7375** [comment]
일단 고쳐졌다고 판단하므로 닫습니다.

**Comment by junsik5477** [comment]
감사합니다....
전과 동일한 문제는 없어졌는데요....
source를 해보니 아래와 같은 메세지가 나오는데요..
원인을 모르겠네요..ㅠㅠ

> source ~/.zshrc
This theme is not available.
_zsh_highlight:34: array parameter region_highlight created globally in
function _zsh_highlight

 ~ -------------------------------------------------------------------------
>
(eval):2: defining function based on alias `fuck'
(eval):2: parse error near `()'




2021년 4월 1일 (목) 오후 4:52, MS_Y ***@***.***>님이 작성:

**Comment by black7375** [comment]
```
This theme is not available.
```
테마 설정파일 때문에 일어나는 것 같습니다.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

주석처리를 하거나, `source /Users/jskim/.zsh/BlaCk-Void.zshrc` 아래에 설정해보세요.


```
_zsh_highlight:34: array parameter region_highlight created globally in
function _zsh_highlight
```
하이라이트 관련 오류 같은데..

```
rm -rf ~/.zplugin/pllugins
```
로 플러그인을 지워보세요.


```
(eval):2: defining function based on alias `fuck'
(eval):2: parse error near `()'
```
음..

```
cd ~/.zsh/
git pull origin master
```
후에 쉘 다시 시작 해보시겠어요?

**Comment by junsik5477** [comment]
우선 [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh 부분을 주석 처리 하였습니다.
주석 처리 하니 정상적으로 적동을 하네요.~

테마만 변경하지 않는다면 문제가 없는거 겠죠?

감사합니다.

2021년 4월 5일 (월) 오후 3:06, MS_Y ***@***.***>님이 작성:

**Comment by black7375** [comment]
에러표시 안나오면 괜찮으실거에요.
리포트 감사합니다.

**Comment by junsik5477** [comment]
아래의 부분을 주석후 다음날이 되면 p10k 설정을 다시 하라는 메세지가 항상 나오네요....
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

2021년 4월 5일 (월) 오후 3:48, MS_Y ***@***.***>님이 작성:

**Comment by black7375** [comment]
제 시스템의 `~/.zshrc`는 다음이 끝입니다.
```shell
export BVZSH_TOOLS="advanced"
source ~/.zsh/BlaCk-Void.zshrc
alias dpython='docker run --rm -i -t -v $(pwd):/ai  alstjr7375/typed:latest-nogpu python'
```

제가 알기로 
https://github.com/black7375/BlaCk-Void-Zsh/blob/36ded43b6fef86626799c0a47029e388d0bf4228/BlaCk-Void.ztheme#L60-L82

처럼 p10k의 테마의 커스텀이 발생하면 설정하라는 메시지가 뜨지 않는게 정상입니다.

어딘가 시스템이 꼬인것 같은데..
일단 zshrc 마지막 자리로 옮기면
```
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```
This theme is not available.는 안나오지 않을까 싶어요.

그래도 안되신다면
```
rm -rf ~/.zsh
rm -rf ~/.zplugin/zplugins
git clone https://github.com/black7375/BlaCk-Void-Zsh.git ~/.zsh
```
을 실행해 재설치를 시도해볼 수 있습니다.

**Comment by junsik5477** [comment]
음...이건 그냥 저의 생각인데요...

맥 os 업그레이드를 통해서 작업을 진행하였을때는 문제 없었는데요...
맥을 초기화 한다음에...macos big sur 11.2.3 을 바로 사용할경우..
BlaCk-Void-Zsh.sh 파일 install 할때부터 에러가 났었거든요...
set brew 함수 부분에서 brew install 다음 parmarter 가 없다는 에러가 났었어요...
brew를 미리 설치하고도 해보고 설치전에 해봐도 동일하게 에러가 발생해서..
제가 set brew 부분을 주석하고 install했거든요...

2021년 4월 7일 (수) 오전 10:26, MS_Y ***@***.***>님이 작성:

**Comment by black7375** [comment]
인스톨스크립트에 문제가 있어서 3월 즈음에 a15b716aed1f4681a065ace614bae1804c2f94db
고치긴 했어요.

카타리나까지는 테스트 했었는데 지금은 맥이 고장나서 테스트를 제대로 못하고 있습니다 ㅠㅠ
