### ISSUE TITLE
Increase contrast between selected tab and other tabs

### ISSUE THREAD

**Issue by samcarter** [black7375/BlaCk-Void-Zsh#28]
Thanks a lot for your beautiful theme! It makes the toolbars so much more compact!

Is there any hack to make the currently selected tab lighter so it stands out more between the other tabs? I assume I need to edit `userChrome.css` to change the colour, but could you give me some pointers for the lines to look at?

<img width="745" alt="Screenshot 2021-08-17 at 18 32 05" src="https://user-images.githubusercontent.com/43832342/129784060-b16db560-976b-4d89-bb2a-d3891731b4db.png">

**Comment by black7375** [comment]
Copied the issue. Check the following: https://github.com/black7375/Firefox-UI-Fix/issues/178
