### ISSUE TITLE
okay now what?

### ISSUE THREAD

**Issue by userx-bw** [black7375/BlaCk-Void-Zsh#3]
I got it installed arcolinux, but now how do I implement it so when I open a terminal I see the changes? I have not found anything in here to tell/show me how to finish what was started.

**Comment by black7375** [comment]
Do you mean uninstall or go back to [Bash/Previous environment Zsh]?

1. Go back to Bash
`sudo chsh -s $(which bash)`

2. Go back to Previous environment Zsh
If the previous configuration files(`~/.zshrc` `~/.zshenv` `~/.zlogin`) exist, it will be backed up with the ".bak" file like `~/.zshrc.bak`.
If not, just clear configuration files.

3. Uninstall
```
rm -rf $BVZSH ~/.zplugin
```
Than please refer to No.1 and No.2.

**Comment by userx-bw** [comment]
thanks, all of this zsh anything is completely new to me
