### ISSUE TITLE
Change on Zplugin repository

### ISSUE THREAD

**Issue by hoon0422** [black7375/BlaCk-Void-Zsh#32]
ZPlugin repository is moved to "https://github.com/zdharma-continuum/zinit.git".

I don't have a screenshot for error messages due to this issue. The messages include that `zplugin` command does not exist.

Here is how I solved this issue. (Environment: Mac OS Monterey)

1. Install "https://github.com/zdharma-continuum/zinit.git" manually.
2. Go to the directory of the installed program (in my case, `~/.local/share/zinit`)
3. Create a link from `zinit.git` directory to `bin`
```bash
 ln -s ~/.local/share/zinit/zinit.git ~/.local/share/zinit/bin
```
4. Change some lines of `~/.zsh/BlaCk-Void.zshrc`
    - `ZPLUGIN_DIR=~/.zplugin` to  ` ZPLUGIN_DIR=~/.local/share/zinit`
    - `ZPLUGIN_BIN=${ZPLUGIN_DIR}/zplugin.zsh` to  `ZPLUGIN_BIN=${ZPLUGIN_DIR}/bin/zinit.zsh`
5. Run `source ~/.zshrc`

**Comment by black7375** [comment]
I had a similar issue in the past, so I wrote a migration code.
https://github.com/black7375/BlaCk-Void-Zsh/blob/master/autoload/zsh-update

I will make the migration progress if the `zsh-update` is executed within a few days.

**Comment by black7375** [comment]
Migration has been applied.

After ``cd $BVZSH && git pull`` due to the structural problems of the old code, you can run the `zsh-update` after restarting
