### ISSUE TITLE
[Question] how to unalias?

### ISSUE THREAD

**Issue by everLEEst** [black7375/BlaCk-Void-Zsh#33]
It might be silly question,
but after installed BlaCk-Void-Zsh,
I couldn't unalias Oh-My-Zsh preset alias commend.
I was unalias gbs in .zshrc
but now it didn't work.
I put same command on .BlaCk-Void.zshrc,
but it didn't work.

where should I put the unalias command?

**Comment by everLEEst** [comment]
안녕하세요.
설명이 길어질 거 같아서 한글로 문의 드리겠습니다.

기본적으로
gbs를 git bisect가 아닌 다른 실행파일로 사용하고 있어서 현재 .zshrc 애서

unalias gbs

및 다른 명령어들을 수행하고 있습니다.

BlaCk-Void-Zsh 설치 이후
alias gbs 시
gbs='git bisect'
로 alias가 선언된 것을 확인하였으며(.zshrc에 명령어는 여전히 존재함)

디버깅을 위해 구간 구간 echo를 넣어보니
unalias gbs까지는 수행되나
source /home/sh10233lee/.zsh/BlaCk-Void.zshrc
이후 로그가 나오지 않는 상황입니다.
수행중 오류가 발생하는 게 아닌가 의심이 되는데
설치가 불완전하게 된 상황인걸까요?

**Comment by black7375** [comment]
아마 소스 후에 `unalias` 작업을 해주시면 될 것 같아요.
```sh
# ~/.zshrc
souce ~/.zsh/BlaCk-Void.zshrc
unalias gbs
```

**Comment by everLEEst** [comment]
> 아마 소스 후에 `unalias` 작업을 해주시면 될 것 같아요.
> 
> ```shell
> # ~/.zshrc
> souce ~/.zsh/BlaCk-Void.zshrc
> unalias gbs
> ```

답변 글에 내용을 추가했는데 그 사이에 답변을 주셨네요ㅎㅎ
여기에 이어서 적겠습니다.


추가 테스트를 위해 BlaCk-Void.zshrc에 로그를 넣어봤는데,
[WARNING]: Console output during zsh initialization detected.
라는 워닝과 함께 기존에 수행되지 않던 .zshrc의 최종 로그까지 찍히는 것을 확인했습니다.

참고로 unalias gbs를 BlaCk-Void.zshrc에 넣어보니
/home/sh10233lee/.zsh/BlaCk-Void.zshrc:unalias:322: no such hash table element: gbs
와 같은 메세지가 나와 unalias가 수행되지 않았습니다.

말씀해주신 것과 같이 source 이후로 변경을 했으나 마찬가지로 unalias가 수행되지 않습니다.
/home/sh10233lee/.zshrc:unalias:117: no such hash table element: gbs

터미널에서 alias gbs를 수행해보면 여전히
gbs='git bisect' 로 잡혀있구요.

**Comment by everLEEst** [comment]
> > 아마 소스 후에 `unalias` 작업을 해주시면 될 것 같아요.
> > ```shell
> > # ~/.zshrc
> > souce ~/.zsh/BlaCk-Void.zshrc
> > unalias gbs
> > ```
> 
> 답변 글에 내용을 추가했는데 그 사이에 답변을 주셨네요ㅎㅎ 여기에 이어서 적겠습니다.
> 
> 추가 테스트를 위해 BlaCk-Void.zshrc에 로그를 넣어봤는데, [WARNING]: Console output during zsh initialization detected. 라는 워닝과 함께 기존에 수행되지 않던 .zshrc의 최종 로그까지 찍히는 것을 확인했습니다.
> 
> 참고로 unalias gbs를 BlaCk-Void.zshrc에 넣어보니 /home/sh10233lee/.zsh/BlaCk-Void.zshrc:unalias:322: no such hash table element: gbs 와 같은 메세지가 나와 unalias가 수행되지 않았습니다.
> 
> 말씀해주신 것과 같이 source 이후로 변경을 했으나 마찬가지로 unalias가 수행되지 않습니다. /home/sh10233lee/.zshrc:unalias:117: no such hash table element: gbs
> 
> 터미널에서 alias gbs를 수행해보면 여전히 gbs='git bisect' 로 잡혀있구요.

아래는 echo를 찍어본 로그입니다만 큰 의미는 없을 거 같습니다.

LSH DEBUG::zshrc start!
LSH DEBUG::zshrc pulin
LSH DEBUG::zshrc oh my zsh!
LSH DEBUG::set env done!
LSH DEBUG::gbs unaliased!
LSH DEBUG::zshrc for black void start.

[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

LSH DEBUG::zshrc for black void init done.
LSH DEBUG::zshrc for black void z-plugin done.
LSH DEBUG::zshrc for black void theme set done.
LSH DEBUG::zshrc for black void plugin set done.
LSH DEBUG::zshrc for black void OMZ bundle done.
LSH DEBUG::zshrc for black void custom bundle step 1 done.
LSH DEBUG::zshrc for black void plugin load done.
LSH DEBUG::zshrc for black void custom bundle step 2 done.
LSH DEBUG::zshrc for black void library setting done.
LSH DEBUG::zshrc for black void bashrc done.
/home/sh10233lee/.zsh/BlaCk-Void.zshrc:unalias:322: no such hash table element: gbs
LSH DEBUG::zshrc for black unalias gbs.
LSH DEBUG::zshrc for black void custom set done.
LSH DEBUG::zshrc for black void is done.
/home/sh10233lee/.zshrc:unalias:117: no such hash table element: gbs
LSH DEBUG::zshrc done!

**Comment by black7375** [comment]
아.. 이유를 알 것 같네요.
요즘에 안건들여서 잠시 까먹었는데, 제 설정은 로드해야하는 플러그인 양이 많은 편이라 성능을 위해 비동기 로드되도록 구성되어 있습니다.

따라서 비동기 큐에서 늦게 처리되도록 우선순위를 설정해주면 될 것 같습니다.

```sh
zinit ice wait"2c" atload"unalias gbs" lucid
zinit light zdharma-continuum/null
```

**Comment by everLEEst** [comment]
> 

말씀해주신대로 추가하니 잘 적용되네요. 도움 감사드립니다!
