### ISSUE TITLE
Bug from pacapt_install excuted by default

### ISSUE THREAD

**Issue by thuako** [black7375/BlaCk-Void-Zsh#35]
There is a bug from pacapt_install executed by default in Redhat enviroment.

https://github.com/black7375/BlaCk-Void-Zsh/blob/3f126333c21f88d24b0ca0bb65a41ab77a355e73/BlaCk-Void-Zsh.sh#L97

In my case, I fix the bug by removing the above line.

**Comment by black7375** [comment]
Thank you for report.
Are you using fedora?

**Comment by thuako-furiosa** [comment]
No, I'm using RHEL8
Thank you.

**Comment by thuako** [comment]
No, I'm using RHEL8

**Comment by thuako** [comment]
한국인이셨네요ㅎ 한글로 하겠습니다.
저는 현재 kubernetes 위에서 Redhat 8 이미지를 기반으로 black-void-zsh 를 사용하고 있습니다.

현 bug 에 대해 업데이트를 하자면
pacapt_install 쪽에서 에러가 발생했었는데 

새로운 kubernetes pod(container) 에서 다시 세팅을 해보니 문제없이 통과하였습니다.
아마 이전 binary 와 pacapt_install 이 호환되지 않는 부분이 있었던 것 같습니다.

해결되었으니 현 issue는 닫도록 하겠습니다.

**Comment by black7375** [comment]
오 만나서 반갑습니다!!
