### ISSUE TITLE
[error] .zinit-load-plugin:source:112: no such file or directory: robbyrussell---oh-my-zsh/plugins/docker/_docker

### ISSUE THREAD

**Issue by swkim0128** [black7375/BlaCk-Void-Zsh#37]
**Describe the bug**
zsh 첫 실행 세팅에서 해당 error message 가 나오는 것을 확인하였습니다.
Black-Void.zshrc 초기 세팅 중 도커 환경이 있다면 /docker/_docker 디렉터리를 접근하는 것을 확인하였습니다.
해당 내용이 필요한 건지 확인이 필요할 것 같습니다.

**To Reproduce**
Tell me when it happens.

 - [ ] Run

**Expected behavior**

**Screenshots**

<img width="976" alt="image" src="https://github.com/black7375/BlaCk-Void-Zsh/assets/12812712/4dc14b85-76de-47fb-8d06-0f689da0ae71">

**Environment (please complete the following information):**
General
 - OS(`uname -a`): Darwin eunsolui-MacBookAir.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103 arm64
 - ZSH(`zsh --version`): zsh 5.9 (x86_64-apple-darwin23.0)

CheckList
 - [x] Use latest commit
 - [ ] Custom in use
 - [ ] SSH

**Additional context**

**Comment by black7375** [comment]
플러그인의 path 정보가 달라졌음을 확인하여 수정하였습니다.

**Comment by swkim0128** [comment]
도움이 되어 좋았습니다~!
