### ISSUE TITLE
Duplicated scripts in autoload

### ISSUE THREAD

**Issue by migmolrod** [black7375/BlaCk-Void-Zsh#4]
The [`autoload/da`](https://github.com/black7375/BlaCk-Void-Zsh/blob/master/autoload/da) (docker start + attach) and the [`autoload/ds`](https://github.com/black7375/BlaCk-Void-Zsh/blob/master/autoload/ds) are doing the same thing.
I suppose you want `da` to do `docker start + attach` and the `ds` to do `docker stop`, right?

**Comment by black7375** [comment]
good report!!
