### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by Peter-Roh** [black7375/BlaCk-Void-Zsh#5]
![Screenshot from 2019-09-05 10-42-31](https://user-images.githubusercontent.com/36218264/64305301-ec384e80-cfc9-11e9-933d-307cf9fa7629.png)

I've installed it and I have only one problem. 
As you see in the picture, I can barely see 'on the master' part. 
How can I change that part to make it vivid?

(I am using ubuntu 19.04)

**Comment by black7375** [comment]
## When using default setting
Create custom theme setting.
```
cp $BVZSH/BlaCk-Void.ztheme ~/.ztheme
```

Change `_powerline-nerd()` 's ##-----Color Set  
```
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='000'               #alpha
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='040'               #green or'165' #purple
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='000'           #alpha
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='040'           #green
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='000'            #alpha
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='208'            #orange
```

Colors refer to `for code ({000..255}) print -P -- "$code: %F{$code}This is how your text would look like%f"`

## When using custom setting
Change to default setting.
```
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='000'               #alpha
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='040'               #green or'165' #purple
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='000'           #alpha
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='040'           #green
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='000'            #alpha
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='208'            #orange
```

**Comment by Peter-Roh** [comment]
Thanks a lot! This helped so much.
