### ISSUE TITLE
Fail to install on MacOS, sed error

### ISSUE THREAD

**Issue by alienzin** [black7375/BlaCk-Void-Zsh#7]
If I run `bash ~/.zsh/BlaCk-Void-Zsh.sh`, I get following error.

`sed: 1: "/Users/alienzin/.zshrc": extra characters at the end of d command`

`sed` command produces the error.
> #Remove zplugin installer contents
> sed -i '/[zZ]plugin/d'  ~/.zshrc`

If I change `sed -i` to `sed -i ''`, then it works fine on my MacOS.

**Comment by black7375** [comment]
Reflected your suggestions.
Thank you 👍
